global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'users_service'
    static_configs:
      - targets: ['localhost:2112']

  - job_name: 'order_service'
    static_configs:
      - targets: ['localhost:2113']

  - job_name: 'instruments_service'
    static_configs:
      - targets: ['localhost:2114']

  - job_name: 'cart_service'
    static_configs:
      - targets: ['localhost:2115']
