// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.30.2
// source: proto/instruments.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InstrumentServiceClient is the client API for InstrumentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InstrumentServiceClient interface {
	CreateInstrument(ctx context.Context, in *CreateInstrumentRequest, opts ...grpc.CallOption) (*CreateInstrumentResponse, error)
	GetAllInstruments(ctx context.Context, in *GetAllInstrumentsRequest, opts ...grpc.CallOption) (*GetAllInstrumentsResponse, error)
	DeleteInstrumentByID(ctx context.Context, in *DeleteInstrumentByIDRequest, opts ...grpc.CallOption) (*DeleteInstrumentByIDResponse, error)
	UpdateInstrumentByID(ctx context.Context, in *UpdateInstrumentByIDRequest, opts ...grpc.CallOption) (*UpdateInstrumentByIDResponse, error)
}

type instrumentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInstrumentServiceClient(cc grpc.ClientConnInterface) InstrumentServiceClient {
	return &instrumentServiceClient{cc}
}

func (c *instrumentServiceClient) CreateInstrument(ctx context.Context, in *CreateInstrumentRequest, opts ...grpc.CallOption) (*CreateInstrumentResponse, error) {
	out := new(CreateInstrumentResponse)
	err := c.cc.Invoke(ctx, "/instruments.InstrumentService/CreateInstrument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instrumentServiceClient) GetAllInstruments(ctx context.Context, in *GetAllInstrumentsRequest, opts ...grpc.CallOption) (*GetAllInstrumentsResponse, error) {
	out := new(GetAllInstrumentsResponse)
	err := c.cc.Invoke(ctx, "/instruments.InstrumentService/GetAllInstruments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instrumentServiceClient) DeleteInstrumentByID(ctx context.Context, in *DeleteInstrumentByIDRequest, opts ...grpc.CallOption) (*DeleteInstrumentByIDResponse, error) {
	out := new(DeleteInstrumentByIDResponse)
	err := c.cc.Invoke(ctx, "/instruments.InstrumentService/DeleteInstrumentByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instrumentServiceClient) UpdateInstrumentByID(ctx context.Context, in *UpdateInstrumentByIDRequest, opts ...grpc.CallOption) (*UpdateInstrumentByIDResponse, error) {
	out := new(UpdateInstrumentByIDResponse)
	err := c.cc.Invoke(ctx, "/instruments.InstrumentService/UpdateInstrumentByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstrumentServiceServer is the server API for InstrumentService service.
// All implementations must embed UnimplementedInstrumentServiceServer
// for forward compatibility
type InstrumentServiceServer interface {
	CreateInstrument(context.Context, *CreateInstrumentRequest) (*CreateInstrumentResponse, error)
	GetAllInstruments(context.Context, *GetAllInstrumentsRequest) (*GetAllInstrumentsResponse, error)
	DeleteInstrumentByID(context.Context, *DeleteInstrumentByIDRequest) (*DeleteInstrumentByIDResponse, error)
	UpdateInstrumentByID(context.Context, *UpdateInstrumentByIDRequest) (*UpdateInstrumentByIDResponse, error)
	mustEmbedUnimplementedInstrumentServiceServer()
}

// UnimplementedInstrumentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInstrumentServiceServer struct {
}

func (UnimplementedInstrumentServiceServer) CreateInstrument(context.Context, *CreateInstrumentRequest) (*CreateInstrumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInstrument not implemented")
}
func (UnimplementedInstrumentServiceServer) GetAllInstruments(context.Context, *GetAllInstrumentsRequest) (*GetAllInstrumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllInstruments not implemented")
}
func (UnimplementedInstrumentServiceServer) DeleteInstrumentByID(context.Context, *DeleteInstrumentByIDRequest) (*DeleteInstrumentByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInstrumentByID not implemented")
}
func (UnimplementedInstrumentServiceServer) UpdateInstrumentByID(context.Context, *UpdateInstrumentByIDRequest) (*UpdateInstrumentByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInstrumentByID not implemented")
}
func (UnimplementedInstrumentServiceServer) mustEmbedUnimplementedInstrumentServiceServer() {}

// UnsafeInstrumentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InstrumentServiceServer will
// result in compilation errors.
type UnsafeInstrumentServiceServer interface {
	mustEmbedUnimplementedInstrumentServiceServer()
}

func RegisterInstrumentServiceServer(s grpc.ServiceRegistrar, srv InstrumentServiceServer) {
	s.RegisterService(&InstrumentService_ServiceDesc, srv)
}

func _InstrumentService_CreateInstrument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstrumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstrumentServiceServer).CreateInstrument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/instruments.InstrumentService/CreateInstrument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstrumentServiceServer).CreateInstrument(ctx, req.(*CreateInstrumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstrumentService_GetAllInstruments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllInstrumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstrumentServiceServer).GetAllInstruments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/instruments.InstrumentService/GetAllInstruments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstrumentServiceServer).GetAllInstruments(ctx, req.(*GetAllInstrumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstrumentService_DeleteInstrumentByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInstrumentByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstrumentServiceServer).DeleteInstrumentByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/instruments.InstrumentService/DeleteInstrumentByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstrumentServiceServer).DeleteInstrumentByID(ctx, req.(*DeleteInstrumentByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstrumentService_UpdateInstrumentByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInstrumentByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstrumentServiceServer).UpdateInstrumentByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/instruments.InstrumentService/UpdateInstrumentByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstrumentServiceServer).UpdateInstrumentByID(ctx, req.(*UpdateInstrumentByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InstrumentService_ServiceDesc is the grpc.ServiceDesc for InstrumentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InstrumentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "instruments.InstrumentService",
	HandlerType: (*InstrumentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInstrument",
			Handler:    _InstrumentService_CreateInstrument_Handler,
		},
		{
			MethodName: "GetAllInstruments",
			Handler:    _InstrumentService_GetAllInstruments_Handler,
		},
		{
			MethodName: "DeleteInstrumentByID",
			Handler:    _InstrumentService_DeleteInstrumentByID_Handler,
		},
		{
			MethodName: "UpdateInstrumentByID",
			Handler:    _InstrumentService_UpdateInstrumentByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/instruments.proto",
}
